#page title
page_title                                : BetterPlates                                          

# App Info
ios_app_id                                : 6740587732                               
ios_app_country                           : us                                        

appstore_link                             : https://apps.apple.com/us/app/betterplates-smart-recipe-app/id6740587732                                          
playstore_link                            :                                           
presskit_download_link                    :                                           

app_icon                                  : assets/appicon.png                      
app_name                                  : BetterPlates                                          
app_price                                 : Free                                           
app_description                           : Smart import your favorite recipes from anywhere on the web. Instantly modify them with AI to fit your custom eating goals.

enable_smart_app_banner                   : true                                      

# Information About Yourself
your_name                                 : Bradley Beeson                                
your_link                                 :
your_city                                 :                                 
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           :
youtube_username                          :
mastodon_link                             : 

# Feature List                            
features                                  :

  - title                                 : AI Recipe Modification
    description                           : Instantly modify any recipe to match your dietary needs, health goals, or preferences using advanced AI.
    fontawesome_icon_name                 : magic
    
  - title                                 : Smart Recipe Import
    description                           : Import recipes from anywhere on the web - websites, Instagram, TikTok, and more with just one tap.
    fontawesome_icon_name                 : file-import

  - title                                 : Shopping Lists
    description                           : Automatically generate shopping lists from your recipes.
    fontawesome_icon_name                 : shopping-cart

  - title                                 : Recipe Organization
    description                           : Easily save and organize your favorite recipes in one place.
    fontawesome_icon_name                 : book

  - title                                 : Recipe Sharing
    description                           : Share your favorite recipes with friends and family.
    fontawesome_icon_name                 : share-alt

# Theme Settings
topbar_color                              : "#2D3047"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

# Header pages
header_pages:
  - _pages/privacypolicy.md
  - _pages/termsofservice.md
  - _pages/help.md

# Disable What's New page
show_changelog                            : false
include_changelog                         : false

cover_image                               : assets/headerimage.jpg
cover_overlay_color                       : "#2D3047"
cover_overlay_transparency                : 0.8

device_color                              : black                                     

body_background_color                     : "#ffffff"

link_color                                : "#419D78"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#2D3047"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#419D78"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
